### ISSUE TITLE
Getting: panic: no such file or directory error

### ISSUE THREAD

**Issue by wallacepf** [AlyRagab/Vault-Audit-Logging#4]
Hello Friend, how are you doing?

I'm trying to implement your small app to help with my use case. I'm logging everything on `stdout` (Monitor and Audit Logs), and this messes with my log collector so, I found your project, which seems amazing for my use case. The problem I'm having should be pretty simple once I'm getting an error from your app saying that it couldn't find the log file. I've reviewed my configs and so far, I have no clue how to solve this so, I'm asking for your help. Here is how I'm implementing your container:

```yaml
  extraContainers:
    - name: vault-audit
      image: alyragab/vault-audit:v1
      imagePullPolicy: Always
      env:
        - name: "AUDIT_FILE_PATH"
          value: "/vault/audit/vault_audit.log"
      volumeMounts:
        - mountPath: /vault/audit
          name: audit
          readOnly: false
```

Here is my audit storage config:

```yaml
  auditStorage:
    enabled: true
    size: 2Gi
    mountPath: "/vault/audit"
    storageClass: null
    accessMode: ReadWriteOnce
```

Here's my `pod describe`

```
 vault-audit:
    Container ID:   docker://66022694fa6658667ea129f0376d5cfe2b66526be5577e045bb1991c741ada59
    Image:          alyragab/vault-audit:v1
    Image ID:       docker-pullable://alyragab/vault-audit@sha256:8e6048ff5acb3eb08c58abf3d0bff507511b833cdbae992acd08dec1f8d7a14c
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sun, 30 Jul 2023 00:02:50 -0300
      Finished:     Sun, 30 Jul 2023 00:02:50 -0300
    Ready:          False
    Restart Count:  6
    Environment:
      AUDIT_FILE_PATH:  /vault/audit/vault_audit.log
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wbr8z (ro)
      /vault/audit from audit (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-vault-0
    ReadOnly:   false
  audit:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  audit-vault-0
    ReadOnly:   false
```

And finally my Vault config:

```terraform
resource "vault_audit" "default" {
  type = "file"

  options = {
    file_path = "/vault/audit/vault_audit.log"
  }
}
```

Any help will be highly appreciated. In case you need more info, let me know.
